//! Veltrix: small utilities for common paths and emoji constants.
//!
//! This crate provides helpers for resolving standard system and user
//! file locations, a small set of emoji constants (behind the `emojis`
//! feature), and convenience error types used across the helpers.

/// Error types and result alias used by Veltrix helpers.
pub mod error;

/// Path helpers and common path-related constants.
pub mod paths;

#[cfg(feature = "unistd")]
/// `unistd` helpers (optional, behind the `unistd` feature).
pub mod unistd;

#[cfg(feature = "emojis")]
/// Emoji constants and lookup helpers (generated by the codegen crate).
pub mod emojis;

/// Re-exported result alias and primary error type for ergonomics.
pub use error::{Result, VeltrixError as Error};
