//! Emoji constants and lookup helpers.
//!
//! The `emojis` module is generated by `veltrix-codegen`. It exposes a
//! large set of emoji constants (in `constants`) and lookup utilities in
//! `details` such as `ALL`, `by_group`, `find_by_emoji` and `find_by_name`.

pub mod constants;
pub mod details;

pub use constants::*;
pub use details::{ALL, Emoji, by_group, by_subgroup, find_by_emoji, find_by_name};
